# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-30 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_prevision_tipobono'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoPrevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.TipoBono')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Prevision')),
            ],
        ),
    ]
