# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-30 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_bonoprevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipobono',
            name='prevision',
        ),
    ]
